version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/bookstore
      - JWT_SECRET=your_jwt_secret_key_here
      - JWT_EXPIRES_IN=24h
    depends_on:
      - mongodb
    networks:
      - bookstore-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - bookstore-network

volumes:
  mongodb_data:

networks:
  bookstore-network:
    driver: bridge 